# fly.toml app configuration file generated for medusabackend on 2023-08-31T00:23:51+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "medusabackend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
